#!/bin/bash  
#SBATCH   --account=gg0302
#SBATCH   --nodes=4
#SBATCH   -n 1024
#SBATCH   --partition=compute
#SBATCH   --time=04:00:00           
#SBATCH   -J  kpp               # Specify job name


echo "Start kpp script execution at $(date)"

srun ./dynho.exe



