! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The ODE Jacobian of Chemical Model File
! 
! Generated by KPP-2.2.1_rs5 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : verwer_Jacobian.f90
! Time                 : Wed Aug  2 21:06:50 2023
! Working directory    : /pfs/data5/home/kit/imk-tro/ii5664/kpp/verwer
! Equation file        : verwer.kpp
! Output root filename : verwer
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE verwer_Jacobian

  USE verwer_Parameters
  USE verwer_JacobianSP

  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Jac_SP - the Jacobian of Variables in sparse matrix representation
!   Arguments :
!      V         - Concentrations of variable species (local)
!      F         - Concentrations of fixed species (local)
!      RCT       - Rate constants (local)
!      JVS       - sparse Jacobian of variables
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Jac_SP ( V, F, RCT, JVS )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
! RCT - Rate constants (local)
  REAL(kind=dp) :: RCT(NREACT)
! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)


! Local variables
! B - Temporary array
  REAL(kind=dp) :: B(41)

! B(1) = dA(1)/dV(17)
  B(1) = RCT(1)
! B(2) = dA(2)/dV(14)
  B(2) = 1.8e-20*V(18)
! B(3) = dA(2)/dV(18)
  B(3) = 1.8e-20*V(14)
! B(4) = dA(3)/dV(16)
  B(4) = 8.1e-18*V(18)
! B(5) = dA(3)/dV(18)
  B(5) = 8.1e-18*V(16)
! B(6) = dA(4)/dV(13)
  B(6) = RCT(4)
! B(7) = dA(5)/dV(13)
  B(7) = RCT(5)
! B(8) = dA(6)/dV(13)
  B(8) = 1e-17*V(20)
! B(9) = dA(6)/dV(20)
  B(9) = 1e-17*V(13)
! B(10) = dA(7)/dV(8)
  B(10) = RCT(7)
! B(11) = dA(8)/dV(8)
  B(11) = 1.6e-17*V(20)
! B(12) = dA(8)/dV(20)
  B(12) = 1.6e-17*V(8)
! B(13) = dA(9)/dV(15)
  B(13) = 1.1e-17*V(18)
! B(14) = dA(9)/dV(18)
  B(14) = 1.1e-17*V(15)
! B(15) = dA(10)/dV(15)
  B(15) = 6.1e-18*V(17)
! B(16) = dA(10)/dV(17)
  B(16) = 6.1e-18*V(15)
! B(17) = dA(11)/dV(9)
  B(17) = 0.00037
! B(18) = dA(12)/dV(18)
  B(18) = 8.1e-18*V(19)
! B(19) = dA(12)/dV(19)
  B(19) = 8.1e-18*V(18)
! B(20) = dA(13)/dV(10)
  B(20) = 0.031*F(2)
! B(22) = dA(14)/dV(17)
  B(22) = 1.1e-17*V(20)
! B(23) = dA(14)/dV(20)
  B(23) = 1.1e-17*V(17)
! B(24) = dA(15)/dV(7)
  B(24) = 80000*F(1)*F(2)
! B(27) = dA(16)/dV(14)
  B(27) = RCT(16)
! B(28) = dA(17)/dV(14)
  B(28) = RCT(17)
! B(29) = dA(18)/dV(5)
  B(29) = 1.7e+06*F(3)
! B(31) = dA(19)/dV(5)
  B(31) = 7.4e+09*F(1)
! B(33) = dA(20)/dV(6)
  B(33) = 8.4e-19*V(20)
! B(34) = dA(20)/dV(20)
  B(34) = 8.4e-19*V(6)
! B(35) = dA(21)/dV(12)
  B(35) = RCT(21)
! B(36) = dA(22)/dV(12)
  B(36) = RCT(22)
! B(37) = dA(23)/dV(14)
  B(37) = 3.1e-23*V(17)
! B(38) = dA(23)/dV(17)
  B(38) = 3.1e-23*V(14)
! B(39) = dA(24)/dV(12)
  B(39) = 1.2e-18*V(17)
! B(40) = dA(24)/dV(17)
  B(40) = 1.2e-18*V(12)
! B(41) = dA(25)/dV(11)
  B(41) = 0.052

! Construct the Jacobian terms from B's
! JVS(1) = Jac_FULL(1,1)
  JVS(1) = 0
! JVS(2) = Jac_FULL(1,8)
  JVS(2) = B(10)
! JVS(3) = Jac_FULL(1,13)
  JVS(3) = B(6)+B(7)+B(8)
! JVS(4) = Jac_FULL(1,20)
  JVS(4) = B(9)
! JVS(5) = Jac_FULL(2,2)
  JVS(5) = 0
! JVS(6) = Jac_FULL(2,17)
  JVS(6) = B(22)
! JVS(7) = Jac_FULL(2,20)
  JVS(7) = B(23)
! JVS(8) = Jac_FULL(3,3)
  JVS(8) = 0
! JVS(9) = Jac_FULL(3,6)
  JVS(9) = B(33)
! JVS(10) = Jac_FULL(3,20)
  JVS(10) = B(34)
! JVS(11) = Jac_FULL(4,4)
  JVS(11) = 0
! JVS(12) = Jac_FULL(4,15)
  JVS(12) = B(13)
! JVS(13) = Jac_FULL(4,18)
  JVS(13) = B(14)
! JVS(14) = Jac_FULL(5,5)
  JVS(14) = -B(29)-B(31)
! JVS(15) = Jac_FULL(5,14)
  JVS(15) = B(27)
! JVS(16) = Jac_FULL(6,6)
  JVS(16) = -B(33)
! JVS(17) = Jac_FULL(6,20)
  JVS(17) = -B(34)
! JVS(18) = Jac_FULL(7,5)
  JVS(18) = B(31)
! JVS(19) = Jac_FULL(7,7)
  JVS(19) = -B(24)
! JVS(20) = Jac_FULL(7,12)
  JVS(20) = B(36)
! JVS(21) = Jac_FULL(7,14)
  JVS(21) = B(28)
! JVS(22) = Jac_FULL(7,17)
  JVS(22) = B(1)
! JVS(23) = Jac_FULL(8,8)
  JVS(23) = -B(10)-B(11)
! JVS(24) = Jac_FULL(8,20)
  JVS(24) = -B(12)
! JVS(25) = Jac_FULL(9,9)
  JVS(25) = -B(17)
! JVS(26) = Jac_FULL(9,15)
  JVS(26) = B(15)
! JVS(27) = Jac_FULL(9,17)
  JVS(27) = B(16)
! JVS(28) = Jac_FULL(10,10)
  JVS(28) = -B(20)
! JVS(29) = Jac_FULL(10,18)
  JVS(29) = B(18)
! JVS(30) = Jac_FULL(10,19)
  JVS(30) = B(19)
! JVS(31) = Jac_FULL(11,11)
  JVS(31) = -B(41)
! JVS(32) = Jac_FULL(11,12)
  JVS(32) = B(39)
! JVS(33) = Jac_FULL(11,17)
  JVS(33) = B(40)
! JVS(34) = Jac_FULL(12,11)
  JVS(34) = B(41)
! JVS(35) = Jac_FULL(12,12)
  JVS(35) = -B(35)-B(36)-B(39)
! JVS(36) = Jac_FULL(12,14)
  JVS(36) = B(37)
! JVS(37) = Jac_FULL(12,17)
  JVS(37) = B(38)-B(40)
! JVS(38) = Jac_FULL(13,10)
  JVS(38) = B(20)
! JVS(39) = Jac_FULL(13,13)
  JVS(39) = -B(6)-B(7)-B(8)
! JVS(40) = Jac_FULL(13,18)
  JVS(40) = 0
! JVS(41) = Jac_FULL(13,19)
  JVS(41) = 0
! JVS(42) = Jac_FULL(13,20)
  JVS(42) = -B(9)
! JVS(43) = Jac_FULL(14,7)
  JVS(43) = B(24)
! JVS(44) = Jac_FULL(14,12)
  JVS(44) = 0
! JVS(45) = Jac_FULL(14,14)
  JVS(45) = -B(2)-B(27)-B(28)-B(37)
! JVS(46) = Jac_FULL(14,17)
  JVS(46) = -B(38)
! JVS(47) = Jac_FULL(14,18)
  JVS(47) = -B(3)
! JVS(48) = Jac_FULL(15,8)
  JVS(48) = B(11)
! JVS(49) = Jac_FULL(15,9)
  JVS(49) = B(17)
! JVS(50) = Jac_FULL(15,15)
  JVS(50) = -B(13)-B(15)
! JVS(51) = Jac_FULL(15,17)
  JVS(51) = -B(16)
! JVS(52) = Jac_FULL(15,18)
  JVS(52) = -B(14)
! JVS(53) = Jac_FULL(15,20)
  JVS(53) = B(12)
! JVS(54) = Jac_FULL(16,6)
  JVS(54) = B(33)
! JVS(55) = Jac_FULL(16,8)
  JVS(55) = B(10)
! JVS(56) = Jac_FULL(16,10)
  JVS(56) = B(20)
! JVS(57) = Jac_FULL(16,13)
  JVS(57) = 2*B(6)+B(8)
! JVS(58) = Jac_FULL(16,16)
  JVS(58) = -B(4)
! JVS(59) = Jac_FULL(16,18)
  JVS(59) = -B(5)
! JVS(60) = Jac_FULL(16,19)
  JVS(60) = 0
! JVS(61) = Jac_FULL(16,20)
  JVS(61) = B(9)+B(34)
! JVS(62) = Jac_FULL(17,9)
  JVS(62) = B(17)
! JVS(63) = Jac_FULL(17,11)
  JVS(63) = B(41)
! JVS(64) = Jac_FULL(17,12)
  JVS(64) = B(36)-B(39)
! JVS(65) = Jac_FULL(17,14)
  JVS(65) = B(2)-B(37)
! JVS(66) = Jac_FULL(17,15)
  JVS(66) = B(13)-B(15)
! JVS(67) = Jac_FULL(17,16)
  JVS(67) = B(4)
! JVS(68) = Jac_FULL(17,17)
  JVS(68) = -B(1)-B(16)-B(22)-B(38)-B(40)
! JVS(69) = Jac_FULL(17,18)
  JVS(69) = B(3)+B(5)+B(14)+B(18)
! JVS(70) = Jac_FULL(17,19)
  JVS(70) = B(19)
! JVS(71) = Jac_FULL(17,20)
  JVS(71) = -B(23)
! JVS(72) = Jac_FULL(18,12)
  JVS(72) = B(35)
! JVS(73) = Jac_FULL(18,14)
  JVS(73) = -B(2)
! JVS(74) = Jac_FULL(18,15)
  JVS(74) = -B(13)
! JVS(75) = Jac_FULL(18,16)
  JVS(75) = -B(4)
! JVS(76) = Jac_FULL(18,17)
  JVS(76) = B(1)
! JVS(77) = Jac_FULL(18,18)
  JVS(77) = -B(3)-B(5)-B(14)-B(18)
! JVS(78) = Jac_FULL(18,19)
  JVS(78) = -B(19)
! JVS(79) = Jac_FULL(18,20)
  JVS(79) = 0
! JVS(80) = Jac_FULL(19,8)
  JVS(80) = B(10)
! JVS(81) = Jac_FULL(19,15)
  JVS(81) = B(13)
! JVS(82) = Jac_FULL(19,17)
  JVS(82) = 0
! JVS(83) = Jac_FULL(19,18)
  JVS(83) = B(14)-B(18)
! JVS(84) = Jac_FULL(19,19)
  JVS(84) = -B(19)
! JVS(85) = Jac_FULL(19,20)
  JVS(85) = 0
! JVS(86) = Jac_FULL(20,5)
  JVS(86) = 2*B(29)
! JVS(87) = Jac_FULL(20,6)
  JVS(87) = -B(33)
! JVS(88) = Jac_FULL(20,8)
  JVS(88) = -B(11)
! JVS(89) = Jac_FULL(20,13)
  JVS(89) = -B(8)
! JVS(90) = Jac_FULL(20,14)
  JVS(90) = 0
! JVS(91) = Jac_FULL(20,16)
  JVS(91) = B(4)
! JVS(92) = Jac_FULL(20,17)
  JVS(92) = -B(22)
! JVS(93) = Jac_FULL(20,18)
  JVS(93) = B(5)
! JVS(94) = Jac_FULL(20,19)
  JVS(94) = 0
! JVS(95) = Jac_FULL(20,20)
  JVS(95) = -B(9)-B(12)-B(23)-B(34)
      
END SUBROUTINE Jac_SP

! End of Jac_SP function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Jac_SP_Vec - function for sparse multiplication: sparse Jacobian times vector
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      UV        - User vector for variables
!      JUV       - Jacobian times user vector
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Jac_SP_Vec ( JVS, UV, JUV )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! UV - User vector for variables
  REAL(kind=dp) :: UV(NVAR)
! JUV - Jacobian times user vector
  REAL(kind=dp) :: JUV(NVAR)

  JUV(1) = JVS(1)*UV(1)+JVS(2)*UV(8)+JVS(3)*UV(13)+JVS(4)*UV(20)
  JUV(2) = JVS(5)*UV(2)+JVS(6)*UV(17)+JVS(7)*UV(20)
  JUV(3) = JVS(8)*UV(3)+JVS(9)*UV(6)+JVS(10)*UV(20)
  JUV(4) = JVS(11)*UV(4)+JVS(12)*UV(15)+JVS(13)*UV(18)
  JUV(5) = JVS(14)*UV(5)+JVS(15)*UV(14)
  JUV(6) = JVS(16)*UV(6)+JVS(17)*UV(20)
  JUV(7) = JVS(18)*UV(5)+JVS(19)*UV(7)+JVS(20)*UV(12)+JVS(21)*UV(14)+JVS(22)*UV(17)
  JUV(8) = JVS(23)*UV(8)+JVS(24)*UV(20)
  JUV(9) = JVS(25)*UV(9)+JVS(26)*UV(15)+JVS(27)*UV(17)
  JUV(10) = JVS(28)*UV(10)+JVS(29)*UV(18)+JVS(30)*UV(19)
  JUV(11) = JVS(31)*UV(11)+JVS(32)*UV(12)+JVS(33)*UV(17)
  JUV(12) = JVS(34)*UV(11)+JVS(35)*UV(12)+JVS(36)*UV(14)+JVS(37)*UV(17)
  JUV(13) = JVS(38)*UV(10)+JVS(39)*UV(13)+JVS(42)*UV(20)
  JUV(14) = JVS(43)*UV(7)+JVS(45)*UV(14)+JVS(46)*UV(17)+JVS(47)*UV(18)
  JUV(15) = JVS(48)*UV(8)+JVS(49)*UV(9)+JVS(50)*UV(15)+JVS(51)*UV(17)+JVS(52)*UV(18)+JVS(53)*UV(20)
  JUV(16) = JVS(54)*UV(6)+JVS(55)*UV(8)+JVS(56)*UV(10)+JVS(57)*UV(13)+JVS(58)*UV(16)+JVS(59)*UV(18)+JVS(61)*UV(20)
  JUV(17) = JVS(62)*UV(9)+JVS(63)*UV(11)+JVS(64)*UV(12)+JVS(65)*UV(14)+JVS(66)*UV(15)+JVS(67)*UV(16)+JVS(68)*UV(17)&
              &+JVS(69)*UV(18)+JVS(70)*UV(19)+JVS(71)*UV(20)
  JUV(18) = JVS(72)*UV(12)+JVS(73)*UV(14)+JVS(74)*UV(15)+JVS(75)*UV(16)+JVS(76)*UV(17)+JVS(77)*UV(18)+JVS(78)*UV(19)
  JUV(19) = JVS(80)*UV(8)+JVS(81)*UV(15)+JVS(83)*UV(18)+JVS(84)*UV(19)
  JUV(20) = JVS(86)*UV(5)+JVS(87)*UV(6)+JVS(88)*UV(8)+JVS(89)*UV(13)+JVS(91)*UV(16)+JVS(92)*UV(17)+JVS(93)*UV(18)&
              &+JVS(95)*UV(20)
      
END SUBROUTINE Jac_SP_Vec

! End of Jac_SP_Vec function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! JacTR_SP_Vec - sparse multiplication: sparse Jacobian transposed times vector
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      UV        - User vector for variables
!      JTUV      - Jacobian transposed times user vector
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE JacTR_SP_Vec ( JVS, UV, JTUV )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! UV - User vector for variables
  REAL(kind=dp) :: UV(NVAR)
! JTUV - Jacobian transposed times user vector
  REAL(kind=dp) :: JTUV(NVAR)

  JTUV(1) = JVS(1)*UV(1)
  JTUV(2) = JVS(5)*UV(2)
  JTUV(3) = JVS(8)*UV(3)
  JTUV(4) = JVS(11)*UV(4)
  JTUV(5) = JVS(14)*UV(5)+JVS(18)*UV(7)+JVS(86)*UV(20)
  JTUV(6) = JVS(9)*UV(3)+JVS(16)*UV(6)+JVS(54)*UV(16)+JVS(87)*UV(20)
  JTUV(7) = JVS(19)*UV(7)+JVS(43)*UV(14)
  JTUV(8) = JVS(2)*UV(1)+JVS(23)*UV(8)+JVS(48)*UV(15)+JVS(55)*UV(16)+JVS(80)*UV(19)+JVS(88)*UV(20)
  JTUV(9) = JVS(25)*UV(9)+JVS(49)*UV(15)+JVS(62)*UV(17)
  JTUV(10) = JVS(28)*UV(10)+JVS(38)*UV(13)+JVS(56)*UV(16)
  JTUV(11) = JVS(31)*UV(11)+JVS(34)*UV(12)+JVS(63)*UV(17)
  JTUV(12) = JVS(20)*UV(7)+JVS(32)*UV(11)+JVS(35)*UV(12)+JVS(64)*UV(17)+JVS(72)*UV(18)
  JTUV(13) = JVS(3)*UV(1)+JVS(39)*UV(13)+JVS(57)*UV(16)+JVS(89)*UV(20)
  JTUV(14) = JVS(15)*UV(5)+JVS(21)*UV(7)+JVS(36)*UV(12)+JVS(45)*UV(14)+JVS(65)*UV(17)+JVS(73)*UV(18)
  JTUV(15) = JVS(12)*UV(4)+JVS(26)*UV(9)+JVS(50)*UV(15)+JVS(66)*UV(17)+JVS(74)*UV(18)+JVS(81)*UV(19)
  JTUV(16) = JVS(58)*UV(16)+JVS(67)*UV(17)+JVS(75)*UV(18)+JVS(91)*UV(20)
  JTUV(17) = JVS(6)*UV(2)+JVS(22)*UV(7)+JVS(27)*UV(9)+JVS(33)*UV(11)+JVS(37)*UV(12)+JVS(46)*UV(14)+JVS(51)*UV(15)&
               &+JVS(68)*UV(17)+JVS(76)*UV(18)+JVS(92)*UV(20)
  JTUV(18) = JVS(13)*UV(4)+JVS(29)*UV(10)+JVS(47)*UV(14)+JVS(52)*UV(15)+JVS(59)*UV(16)+JVS(69)*UV(17)+JVS(77)*UV(18)&
               &+JVS(83)*UV(19)+JVS(93)*UV(20)
  JTUV(19) = JVS(30)*UV(10)+JVS(70)*UV(17)+JVS(78)*UV(18)+JVS(84)*UV(19)
  JTUV(20) = JVS(4)*UV(1)+JVS(7)*UV(2)+JVS(10)*UV(3)+JVS(17)*UV(6)+JVS(24)*UV(8)+JVS(42)*UV(13)+JVS(53)*UV(15)+JVS(61)&
               &*UV(16)+JVS(71)*UV(17)+JVS(95)*UV(20)
      
END SUBROUTINE JacTR_SP_Vec

! End of JacTR_SP_Vec function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE verwer_Jacobian

