C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C Parameter Header File                                            
C                                                                  
C Generated by KPP-2.2.1_rs5 symbolic chemistry Kinetics PreProcessor
C       (http://www.cs.vt.edu/~asandu/Software/KPP)                
C KPP is distributed under GPL, the general public licence         
C       (http://www.gnu.org/copyleft/gpl.html)                     
C (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           
C (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            
C     With important contributions from:                           
C        M. Damian, Villanova University, USA                      
C        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
C                                                                  
C File                 : verwer_Parameters.h                       
C Time                 : Mon Jul 31 15:37:30 2023                  
C Working directory    : /pfs/data5/home/kit/imk-tro/ii5664/kpp/verwer
C Equation file        : verwer.kpp                                
C Output root filename : verwer                                    
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




C NSPEC - Number of chemical species                               
      INTEGER NSPEC
      PARAMETER ( NSPEC = 25 )
C NVAR - Number of Variable species                                
      INTEGER NVAR
      PARAMETER ( NVAR = 20 )
C NVARACT - Number of Active species                               
      INTEGER NVARACT
      PARAMETER ( NVARACT = 16 )
C NFIX - Number of Fixed species                                   
      INTEGER NFIX
      PARAMETER ( NFIX = 5 )
C NREACT - Number of reactions                                     
      INTEGER NREACT
      PARAMETER ( NREACT = 25 )
C NVARST - Starting of variables in conc. vect.                    
      INTEGER NVARST
      PARAMETER ( NVARST = 1 )
C NFIXST - Starting of fixed in conc. vect.                        
      INTEGER NFIXST
      PARAMETER ( NFIXST = 21 )
C NONZERO - Number of nonzero entries in Jacobian                  
      INTEGER NONZERO
      PARAMETER ( NONZERO = 86 )
C LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
      INTEGER LU_NONZERO
      PARAMETER ( LU_NONZERO = 95 )
C CNVAR - (NVAR+1) Number of elements in compressed row format     
      INTEGER CNVAR
      PARAMETER ( CNVAR = 21 )
C CNEQN - (NREACT+1) Number stoicm elements in compressed col format
      INTEGER CNEQN
      PARAMETER ( CNEQN = 26 )
C NHESS - Length of Sparse Hessian                                 
      INTEGER NHESS
      PARAMETER ( NHESS = 39 )
C NLOOKAT - Number of species to look at                           
      INTEGER NLOOKAT
      PARAMETER ( NLOOKAT = 25 )
C NMONITOR - Number of species to monitor                          
      INTEGER NMONITOR
      PARAMETER ( NMONITOR = 1 )
C NMASS - Number of atoms to check mass balance                    
      INTEGER NMASS
      PARAMETER ( NMASS = 1 )

C Index declaration for variable species in C and VAR              
C   VAR(ind_spc) = C(ind_spc)                                      

      INTEGER ind_CO
      PARAMETER ( ind_CO = 1 )
      INTEGER ind_HNO3
      PARAMETER ( ind_HNO3 = 2 )
      INTEGER ind_SO4
      PARAMETER ( ind_SO4 = 3 )
      INTEGER ind_XO2
      PARAMETER ( ind_XO2 = 4 )
      INTEGER ind_O1D
      PARAMETER ( ind_O1D = 5 )
      INTEGER ind_SO2
      PARAMETER ( ind_SO2 = 6 )
      INTEGER ind_O3P
      PARAMETER ( ind_O3P = 7 )
      INTEGER ind_ALD2
      PARAMETER ( ind_ALD2 = 8 )
      INTEGER ind_PAN
      PARAMETER ( ind_PAN = 9 )
      INTEGER ind_CH3O
      PARAMETER ( ind_CH3O = 10 )
      INTEGER ind_N2O5
      PARAMETER ( ind_N2O5 = 11 )
      INTEGER ind_NO3
      PARAMETER ( ind_NO3 = 12 )
      INTEGER ind_HCHO
      PARAMETER ( ind_HCHO = 13 )
      INTEGER ind_O3
      PARAMETER ( ind_O3 = 14 )
      INTEGER ind_C2O3
      PARAMETER ( ind_C2O3 = 15 )
      INTEGER ind_HO2
      PARAMETER ( ind_HO2 = 16 )
      INTEGER ind_NO2
      PARAMETER ( ind_NO2 = 17 )
      INTEGER ind_NO
      PARAMETER ( ind_NO = 18 )
      INTEGER ind_CH3O2
      PARAMETER ( ind_CH3O2 = 19 )
      INTEGER ind_OH
      PARAMETER ( ind_OH = 20 )

C Index declaration for fixed species in C                         
C   C(ind_spc)                                                     

      INTEGER ind_AIR
      PARAMETER ( ind_AIR = 21 )
      INTEGER ind_M
      PARAMETER ( ind_M = 22 )
      INTEGER ind_O2
      PARAMETER ( ind_O2 = 23 )
      INTEGER ind_H2O
      PARAMETER ( ind_H2O = 24 )
      INTEGER ind_H2
      PARAMETER ( ind_H2 = 25 )

C Index declaration for fixed species in FIX                       
C    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)                 

      INTEGER indf_AIR
      PARAMETER ( indf_AIR = 1 )
      INTEGER indf_M
      PARAMETER ( indf_M = 2 )
      INTEGER indf_O2
      PARAMETER ( indf_O2 = 3 )
      INTEGER indf_H2O
      PARAMETER ( indf_H2O = 4 )
      INTEGER indf_H2
      PARAMETER ( indf_H2 = 5 )

C NJVRP - Length of sparse Jacobian JVRP                           
      INTEGER NJVRP
      PARAMETER ( NJVRP = 36 )

C NSTOICM - Length of Sparse Stoichiometric Matrix                 
      INTEGER NSTOICM
      PARAMETER ( NSTOICM = 75 )
