! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Hessian Data Structures File
! 
! Generated by KPP-2.2.1_rs5 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : verwer_HessianSP.f90
! Time                 : Wed Aug  2 21:06:50 2023
! Working directory    : /pfs/data5/home/kit/imk-tro/ii5664/kpp/verwer
! Equation file        : verwer.kpp
! Output root filename : verwer
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE verwer_HessianSP

  PUBLIC
  SAVE


! Hessian Sparse Data
! 

  INTEGER, PARAMETER, DIMENSION(39) :: IHESS_I = (/ &
       1,  2,  3,  4,  6,  8,  9, 10, 11, 12, 12, 13, &
      14, 14, 15, 15, 15, 16, 16, 16, 17, 17, 17, 17, &
      17, 17, 17, 17, 18, 18, 18, 18, 19, 19, 20, 20, &
      20, 20, 20 /)

  INTEGER, PARAMETER, DIMENSION(39) :: IHESS_J = (/ &
      13, 17,  6, 15,  6,  8, 15, 18, 12, 12, 14, 13, &
      14, 14,  8, 15, 15,  6, 13, 16, 12, 14, 14, 15, &
      15, 16, 17, 18, 14, 15, 16, 18, 15, 18,  6,  8, &
      13, 16, 17 /)

  INTEGER, PARAMETER, DIMENSION(39) :: IHESS_K = (/ &
      20, 20, 20, 18, 20, 20, 17, 19, 17, 17, 17, 20, &
      17, 18, 20, 17, 18, 20, 20, 18, 17, 17, 18, 17, &
      18, 18, 20, 19, 18, 18, 18, 19, 18, 19, 20, 20, &
      20, 18, 20 /)


END MODULE verwer_HessianSP

