! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Main Program File
! 
! Generated by KPP-2.2.1_rs5 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : verwer_Main.f90
! Time                 : Wed Aug  2 21:06:50 2023
! Working directory    : /pfs/data5/home/kit/imk-tro/ii5664/kpp/verwer
! Equation file        : verwer.kpp
! Output root filename : verwer
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

PROGRAM verwer_Driver
  USE verwer_Model
  USE verwer_Initialize, ONLY: Initialize

  IMPLICIT NONE

  REAL(kind=dp), ALLOCATABLE :: CHOLDER(:,:)
  REAL(kind=dp) :: T, DVAL(NSPEC), num
  REAL(kind=dp) :: RSTATE(20)
  INTEGER :: counter, skip, i, rank, comsize, ierr
  REAL(kind=dp) :: start, finish
  INTEGER :: j, experiment, counter2
  INTEGER :: margin, request, Tlength, tag, writter

  STEPMIN = 0.0d0
  STEPMAX = 0.0d0

  DO i = 1, NVAR
    RTOL(i) = 1.0d-4
    ATOL(i) = 1.0d-3
  END DO

  Tlength = 60 * 10 + 1 
  ALLOCATE(CHOLDER(Tlength, NSPEC + 1))

  DO experiment = 1, 1000
    counter = 0
    counter2 = 0

    PRINT *, "Ex No ", experiment
  
    CALL Initialize()

    !~~~> Time loop
    T = TSTART
    CHOLDER = 0.0

    PRINT *, "Starting Time Loop"

kron: DO WHILE (T < TEND)
         TIME = T   
         CALL GetMass(C, DVAL)               
         CHOLDER(counter2 + 1, 1) = T
         CHOLDER(counter2 + 1, 2:NSPEC + 1) = C(1:NSPEC)
         CALL Update_SUN() 
         CALL Update_RCONST()
         CALL INTEGRATE(TIN = T, TOUT = T + DT, RSTATUS_U = RSTATE, &
                        ICNTRL_U = (/ 0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 /))
         T = RSTATE(1)
         counter2 = counter2 + 1
         counter = counter + 1
      ENDDO kron

      CALL cpu_time(finish)
      PRINT '("Time = ", F6.3, " seconds.")', finish - start
      PRINT *, "Loop is finished"

      !~~~> End Time loop
      CALL GetMass(C, DVAL)
      CHOLDER(counter2 + 1, 1) = T
      CHOLDER(counter2 + 1, 2:NSPEC + 1) = C(1:NSPEC)
      TIME = T
      CALL InitSaveData(experiment)
      DO j = 1, Tlength
        TIME = CHOLDER(j, 1)
        C(1:NSPEC) = CHOLDER(j, 2:NSPEC + 1) 
        CALL SaveData(experiment)
      END DO
      CALL CloseSaveData(experiment)
  END DO

  991 FORMAT(F6.1, '%. T=', E9.3, 2X, 200(A, '=', E11.4, '; '))  !!!!!!

END PROGRAM verwer_Driver

! End of MAIN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
