! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Stoichiometric Data Structures File
! 
! Generated by KPP-2.2.1_rs5 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : verwer_StoichiomSP.f90
! Time                 : Wed Aug  2 21:06:50 2023
! Working directory    : /pfs/data5/home/kit/imk-tro/ii5664/kpp/verwer
! Equation file        : verwer.kpp
! Output root filename : verwer
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE verwer_StoichiomSP

  USE verwer_Precision
  PUBLIC
  SAVE


! Row-compressed sparse data for the Jacobian of reaction products JVRP

  INTEGER, PARAMETER, DIMENSION(26) :: CROW_JVRP = (/ &
       1,  2,  4,  6,  7,  8, 10, 11, 13, 15, 17, 18, &
      20, 21, 23, 24, 25, 26, 27, 28, 30, 31, 32, 34, &
      36, 37 /)

  INTEGER, PARAMETER, DIMENSION(36) :: ICOL_JVRP = (/ &
      17, 14, 18, 16, 18, 13, 13, 13, 20,  8,  8, 20, &
      15, 18, 15, 17,  9, 18, 19, 10, 17, 20,  7, 14, &
      14,  5,  5,  6, 20, 12, 12, 14, 17, 12, 17, 10 /)

  INTEGER, PARAMETER, DIMENSION(36) :: IROW_JVRP = (/ &
       1,  2,  2,  3,  3,  4,  5,  6,  6,  7,  8,  8, &
       9,  9, 10, 10, 11, 12, 12, 13, 14, 14, 15, 16, &
      17, 18, 19, 20, 20, 21, 22, 23, 23, 24, 24, 24 /)



!  Stoichiometric Matrix in Compressed Column Sparse Format


  INTEGER, PARAMETER, DIMENSION(26) :: CCOL_STOICM = (/ &
       1,  4,  7, 11, 14, 16, 20, 24, 27, 32, 35, 38, &
      42, 45, 48, 50, 52, 54, 56, 58, 62, 64, 67, 70, &
      73, 76 /)

  INTEGER, PARAMETER, DIMENSION(75) :: IROW_STOICM = (/ &
       7, 17, 18, 14, 17, 18, 16, 17, 18, 20,  1, 13, &
      16,  1, 13,  1, 13, 16, 20,  1,  8, 16, 19,  8, &
      15, 20,  4, 15, 17, 18, 19,  9, 15, 17,  9, 15, &
      17, 10, 17, 18, 19, 10, 13, 16,  2, 17, 20,  7, &
      14,  5, 14,  7, 14,  5, 20,  5,  7,  3,  6, 16, &
      20, 12, 18,  7, 12, 17, 12, 14, 17, 11, 12, 17, &
      11, 12, 17 /)

  INTEGER, PARAMETER, DIMENSION(75) :: ICOL_STOICM = (/ &
       1,  1,  1,  2,  2,  2,  3,  3,  3,  3,  4,  4, &
       4,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,  8, &
       8,  8,  9,  9,  9,  9,  9, 10, 10, 10, 11, 11, &
      11, 12, 12, 12, 12, 13, 13, 13, 14, 14, 14, 15, &
      15, 16, 16, 17, 17, 18, 18, 19, 19, 20, 20, 20, &
      20, 21, 21, 22, 22, 22, 23, 23, 23, 24, 24, 24, &
      25, 25, 25 /)

  REAL(kind=dp), PARAMETER, DIMENSION(75) :: STOICM = (/ &
       1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp, &
       -1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp, &
       1.000000e+00_dp,  -1.000000e+00_dp,  2.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp, &
       1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp, &
       -1.000000e+00_dp,  1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp, &
       -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp, &
       1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp, &
       1.000000e+00_dp,  1.000000e+00_dp,  1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp, &
       -1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  1.000000e+00_dp,  1.000000e+00_dp, &
       -1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  1.000000e+00_dp, &
       -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp,  2.000000e+00_dp, &
       -1.000000e+00_dp,  1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp, &
       -1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp, &
       1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp, &
       -1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  1.000000e+00_dp /)


END MODULE verwer_StoichiomSP

