! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Jacobian Data Structures File
! 
! Generated by KPP-2.2.1_rs5 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : verwer_JacobianSP.f90
! Time                 : Wed Aug  2 21:06:50 2023
! Working directory    : /pfs/data5/home/kit/imk-tro/ii5664/kpp/verwer
! Equation file        : verwer.kpp
! Output root filename : verwer
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE verwer_JacobianSP

  PUBLIC
  SAVE


! Sparse Jacobian Data


  INTEGER, PARAMETER, DIMENSION(95) :: LU_IROW = (/ &
       1,  1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4, &
       4,  5,  5,  6,  6,  7,  7,  7,  7,  7,  8,  8, &
       9,  9,  9, 10, 10, 10, 11, 11, 11, 12, 12, 12, &
      12, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 15, &
      15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, &
      16, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 18, &
      18, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, &
      19, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20 /)

  INTEGER, PARAMETER, DIMENSION(95) :: LU_ICOL = (/ &
       1,  8, 13, 20,  2, 17, 20,  3,  6, 20,  4, 15, &
      18,  5, 14,  6, 20,  5,  7, 12, 14, 17,  8, 20, &
       9, 15, 17, 10, 18, 19, 11, 12, 17, 11, 12, 14, &
      17, 10, 13, 18, 19, 20,  7, 12, 14, 17, 18,  8, &
       9, 15, 17, 18, 20,  6,  8, 10, 13, 16, 18, 19, &
      20,  9, 11, 12, 14, 15, 16, 17, 18, 19, 20, 12, &
      14, 15, 16, 17, 18, 19, 20,  8, 15, 17, 18, 19, &
      20,  5,  6,  8, 13, 14, 16, 17, 18, 19, 20 /)

  INTEGER, PARAMETER, DIMENSION(21) :: LU_CROW = (/ &
       1,  5,  8, 11, 14, 16, 18, 23, 25, 28, 31, 34, &
      38, 43, 48, 54, 62, 72, 80, 86, 96 /)

  INTEGER, PARAMETER, DIMENSION(21) :: LU_DIAG = (/ &
       1,  5,  8, 11, 14, 16, 19, 23, 25, 28, 31, 35, &
      39, 45, 50, 58, 68, 77, 84, 95, 96 /)


END MODULE verwer_JacobianSP

