! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The ODE Function of Chemical Model File
! 
! Generated by KPP-2.2.1_rs5 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : verwer_Function.f90
! Time                 : Wed Aug  2 21:06:50 2023
! Working directory    : /pfs/data5/home/kit/imk-tro/ii5664/kpp/verwer
! Equation file        : verwer.kpp
! Output root filename : verwer
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE verwer_Function

  USE verwer_Parameters
  IMPLICIT NONE

! A - Rate for each equation
  REAL(kind=dp) :: A(NREACT)

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Fun - time derivatives of variables - Agregate form
!   Arguments :
!      V         - Concentrations of variable species (local)
!      F         - Concentrations of fixed species (local)
!      RCT       - Rate constants (local)
!      Vdot      - Time derivative of variable species concentrations
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Fun ( V, F, RCT, Vdot )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
! RCT - Rate constants (local)
  REAL(kind=dp) :: RCT(NREACT)
! Vdot - Time derivative of variable species concentrations
  REAL(kind=dp) :: Vdot(NVAR)


! Computation of equation rates
  A(1) = RCT(1)*V(17)
  A(2) = 1.8e-20*V(14)*V(18)
  A(3) = 8.1e-18*V(16)*V(18)
  A(4) = RCT(4)*V(13)
  A(5) = RCT(5)*V(13)
  A(6) = 1e-17*V(13)*V(20)
  A(7) = RCT(7)*V(8)
  A(8) = 1.6e-17*V(8)*V(20)
  A(9) = 1.1e-17*V(15)*V(18)
  A(10) = 6.1e-18*V(15)*V(17)
  A(11) = 0.00037*V(9)
  A(12) = 8.1e-18*V(18)*V(19)
  A(13) = 0.031*V(10)*F(2)
  A(14) = 1.1e-17*V(17)*V(20)
  A(15) = 80000*V(7)*F(1)*F(2)
  A(16) = RCT(16)*V(14)
  A(17) = RCT(17)*V(14)
  A(18) = 1.7e+06*V(5)*F(3)
  A(19) = 7.4e+09*V(5)*F(1)
  A(20) = 8.4e-19*V(6)*V(20)
  A(21) = RCT(21)*V(12)
  A(22) = RCT(22)*V(12)
  A(23) = 3.1e-23*V(14)*V(17)
  A(24) = 1.2e-18*V(12)*V(17)
  A(25) = 0.052*V(11)

! Aggregate function
  Vdot(1) = A(4)+A(5)+A(6)+A(7)
  Vdot(2) = A(14)
  Vdot(3) = A(20)
  Vdot(4) = A(9)
  Vdot(5) = A(16)-A(18)-A(19)
  Vdot(6) = -A(20)
  Vdot(7) = A(1)-A(15)+A(17)+A(19)+A(22)
  Vdot(8) = -A(7)-A(8)
  Vdot(9) = A(10)-A(11)
  Vdot(10) = A(12)-A(13)
  Vdot(11) = A(24)-A(25)
  Vdot(12) = -A(21)-A(22)+A(23)-A(24)+A(25)
  Vdot(13) = -A(4)-A(5)-A(6)+A(13)
  Vdot(14) = -A(2)+A(15)-A(16)-A(17)-A(23)
  Vdot(15) = A(8)-A(9)-A(10)+A(11)
  Vdot(16) = -A(3)+2*A(4)+A(6)+A(7)+A(13)+A(20)
  Vdot(17) = -A(1)+A(2)+A(3)+A(9)-A(10)+A(11)+A(12)-A(14)+A(22)-A(23)-A(24)+A(25)
  Vdot(18) = A(1)-A(2)-A(3)-A(9)-A(12)+A(21)
  Vdot(19) = A(7)+A(9)-A(12)
  Vdot(20) = A(3)-A(6)-A(8)-A(14)+2*A(18)-A(20)
      
END SUBROUTINE Fun

! End of Fun function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE verwer_Function

