! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.2.1_rs5 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : verwer_Monitor.f90
! Time                 : Wed Aug  2 21:06:50 2023
! Working directory    : /pfs/data5/home/kit/imk-tro/ii5664/kpp/verwer
! Equation file        : verwer.kpp
! Output root filename : verwer
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE verwer_Monitor


  CHARACTER(LEN=32), PARAMETER, DIMENSION(24) :: SPC_NAMES = (/ &
     'CO                              ','HNO3                            ','SO4                             ', &
     'XO2                             ','O1D                             ','SO2                             ', &
     'O3P                             ','ALD2                            ','PAN                             ', &
     'CH3O                            ','N2O5                            ','NO3                             ', &
     'HCHO                            ','O3                              ','C2O3                            ', &
     'HO2                             ','NO2                             ','NO                              ', &
     'CH3O2                           ','OH                              ','AIR                             ', &
     'O2                              ','H2O                             ','H2                              ' /)

  INTEGER, PARAMETER, DIMENSION(24) :: LOOKAT = (/ &
       1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, &
      13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24 /)

  INTEGER, PARAMETER, DIMENSION(1) :: MONITOR = (/ &
      13 /)

  CHARACTER(LEN=32), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(25) :: EQN_NAMES = (/ &
     '           NO2 --> O3P + NO                                                                         ', &
     '       O3 + NO --> NO2                                                                              ', &
     '      HO2 + NO --> NO2 + OH                                                                         ', &
     '          HCHO --> CO + 2 HO2                                                                       ', &
     '          HCHO --> CO + H2                                                                          ', &
     '     HCHO + OH --> CO + HO2 + H2O                                                                   ', &
     '          ALD2 --> CO + HO2 + CH3O2                                                                 ', &
     '     ALD2 + OH --> C2O3                                                                             ', &
     '     C2O3 + NO --> XO2 + NO2 + CH3O2                                                                ', &
     '    C2O3 + NO2 --> PAN                                                                              ', &
     '           PAN --> C2O3 + NO2                                                                       ', &
     '    NO + CH3O2 --> CH3O + NO2                                                                       ', &
     '     CH3O + O2 --> HCHO + HO2                                                                       ', &
     '      NO2 + OH --> HNO3                                                                             ', &
     'O3P + AIR + O2 --> O3                                                                               ', &
     '            O3 --> O1D                                                                              ', &
     '            O3 --> O3P                                                                              ', &
     '     O1D + H2O --> 2 OH                                                                             ', &
     '     O1D + AIR --> O3P                                                                              ', &
     '      SO2 + OH --> SO4 + HO2                                                                        ', &
     '           NO3 --> NO                                                                               ', &
     '           NO3 --> O3P + NO2                                                                        ', &
     '      O3 + NO2 --> NO3                                                                              ', &
     '     NO3 + NO2 --> N2O5                                                                             ', &
     '          N2O5 --> NO3 + NO2                                                                        ' /)

! INLINED global variables

! End INLINED global variables


END MODULE verwer_Monitor
