! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.1_rs5 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : verwer_Parameters.f90
! Time                 : Wed Aug  2 21:06:50 2023
! Working directory    : /pfs/data5/home/kit/imk-tro/ii5664/kpp/verwer
! Equation file        : verwer.kpp
! Output root filename : verwer
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE verwer_Parameters

  USE verwer_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 24 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 20 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 16 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 4 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 25 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 21 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 86 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 95 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 21 
! CNEQN - (NREACT+1) Number stoicm elements in compressed col format
  INTEGER, PARAMETER :: CNEQN = 26 
! NHESS - Length of Sparse Hessian
  INTEGER, PARAMETER :: NHESS = 39 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 24 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 1 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_CO = 1 
  INTEGER, PARAMETER :: ind_HNO3 = 2 
  INTEGER, PARAMETER :: ind_SO4 = 3 
  INTEGER, PARAMETER :: ind_XO2 = 4 
  INTEGER, PARAMETER :: ind_O1D = 5 
  INTEGER, PARAMETER :: ind_SO2 = 6 
  INTEGER, PARAMETER :: ind_O3P = 7 
  INTEGER, PARAMETER :: ind_ALD2 = 8 
  INTEGER, PARAMETER :: ind_PAN = 9 
  INTEGER, PARAMETER :: ind_CH3O = 10 
  INTEGER, PARAMETER :: ind_N2O5 = 11 
  INTEGER, PARAMETER :: ind_NO3 = 12 
  INTEGER, PARAMETER :: ind_HCHO = 13 
  INTEGER, PARAMETER :: ind_O3 = 14 
  INTEGER, PARAMETER :: ind_C2O3 = 15 
  INTEGER, PARAMETER :: ind_HO2 = 16 
  INTEGER, PARAMETER :: ind_NO2 = 17 
  INTEGER, PARAMETER :: ind_NO = 18 
  INTEGER, PARAMETER :: ind_CH3O2 = 19 
  INTEGER, PARAMETER :: ind_OH = 20 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_AIR = 21 
  INTEGER, PARAMETER :: ind_O2 = 22 
  INTEGER, PARAMETER :: ind_H2O = 23 
  INTEGER, PARAMETER :: ind_H2 = 24 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_AIR = 1 
  INTEGER, PARAMETER :: indf_O2 = 2 
  INTEGER, PARAMETER :: indf_H2O = 3 
  INTEGER, PARAMETER :: indf_H2 = 4 

! NJVRP - Length of sparse Jacobian JVRP
  INTEGER, PARAMETER :: NJVRP = 36 

! NSTOICM - Length of Sparse Stoichiometric Matrix
  INTEGER, PARAMETER :: NSTOICM = 75 

END MODULE verwer_Parameters

